parameters:
#    mayhem_blog.example.class: Mayhem\BlogBundle\Example

services:
#    mayhem_blog.example:
#        class: %mayhem_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
