# src/Mayhem/BlogBundle/Resources/config/routing.yml

mayhemblog_accueil:
    path:      /{page}
    defaults:  { _controller: MayhemBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d*

mayhemblog_voir:
    path:      /article/{id}
    defaults:  { _controller: MayhemBlogBundle:Blog:voir }
    requirements:
        id:  \d+

mayhemblog_ajouter:
    path:      /ajouter
    defaults:  { _controller: MayhemBlogBundle:Blog:ajouter }

mayhemblog_modifier:
    path:      /modifier/{id}
    defaults:  { _controller: MayhemBlogBundle:Blog:modifier }
    requirements:
        id:  \d+

mayhemblog_supprimer:
    path:      /supprimer/{id}
    defaults:  { _controller: MayhemBlogBundle:Blog:supprimer }
    requirements:
        id:  \d+